version: '3'
services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kinder_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/kinder_db
    ports:
      - "5000:5000"
