name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        ls -l
        echo "Docker login"
        echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB --password-stdin
        echo "Running build..."
        docker build ./docker -t kinderweb_web
        echo "Pushing image..."
        docker tag kinderweb_web:latest lightning53/kinderweb:web
        docker push lightning53/kinderweb:web
        echo "Done!"
