name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        ls -l
        echo "Initializing Docker"
        echo "Running build..."
        docker build . -t kinderweb_web-latest
        echo "Pushing image..."
        docker push kinderweb_web-latest
        echo "Done!"
