name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        ls -l
        echo "Docker login"
        docker login -u $DOCKER_HUB - p $DOCKER_HUB_KEY
        echo "Running build..."
        docker build ./docker -t kinderweb_web
        echo "Pushing image..."
        docker push $DOCKER_HUB - p /kinderweb:web
        echo "Done!"
